version: '3'
services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    labels:
      - traefik.tls.certificates.certFile
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./http.conf/:/etc/traefik/conf/

  api:
    image: ghcr.io/killian-mahe/lore-weaver:main
    container_name: lore-weaver-api
    labels:
      - traefik.http.routers.api.rule=Host(`loreweaver.killianmahe.fr`) && PrefixPath(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.services.api.loadbalancer.server.port=8087

#  chroma-db: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
#    image: chromadb/chroma:latest # Specifying the latest available image - modify if you want a specific version
#    container_name: chroma-db
#    networks:
#      - chroma-net # All of the containers will join the same Docker bridge network