entryPoints:
  websecure:
    address: ':443'

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: true
      email: "postmaster@killianmahe.fr"
      storage: "/letsencrypt/acme.json"

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf/
