entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'

api:
  insecure: true

log:
  level: DEBUG

providers:
  file:
    directory: /etc/traefik/conf/
    watch: true
  docker: {}
