entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: true
      email: killianmahe.pro@gmail.com
      storage: /letsencrypt/acme.json

api:
  insecure: true

providers:
  docker: {}
